name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Write value to Properties-file
        run: sed -ir "s/^[#]*\s*version=.*/version=${{ steps.get_version.outputs.VERSION }}/" gradle.properties

      - name: Test
        run: cat gradle.properties

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew createSwiftPackage

      - name: Copy Package.swift to root
        run: cp swiftpackage/Package.swift Package.swift

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: swiftpackage/GrowthBook.zip

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: Poc/RemoveNetworkLayer
